### ISSUE TITLE
训练时的错误，加载数据时，’text‘属性无法找到。拜托大佬帮忙指导一下

### ISSUE THREAD

**Issue by paipaipaidaxing** [yangjianxin1/CLIP-Chinese#3]
![image](https://user-images.githubusercontent.com/25336067/234166409-fd5d8756-968d-468e-a7a4-2ba0f6f23c06.png)
KeyError: 'text'

**Comment by paipaipaidaxing** [comment]
为什么txt信息无法传入到模型中？

**Comment by paipaipaidaxing** [comment]
解决了，transformer版本问题

**Comment by linwhitehat** [comment]
> 解决了，transformer版本问题

请问你使用的是哪个版本，因为低版本会导致运算报错，高版本则有你显示的这个问题

**Comment by paipaipaidaxing** [comment]
> > 解决了，transformer版本问题
> 
> 请问你使用的是哪个版本，因为低版本会导致运算报错，高版本则有你显示的这个问题

transformers       4.18.0
